### Create hotel
POST http://localhost:8800/api/hotels
Content-Type: application/json

{
  "name": "Hotel California",
  "type": "Hotel",
  "city": "Los Angeles",
  "address": "123 Sunset Blvd",
  "distance": "2km",
  "title": "Best hotel",
  "desc": "A lovely hotel in the heart of the city.",
  "cheapestPrice": 100
}

### Update hotel
PUT http://localhost:8800/api/hotels/68bc51f97e5e7f053fe04e90
Content-Type: application/json

{
  "name": "Hotel Awesome"
}

### Get hotels
GET http://localhost:8800/api/hotels
Content-Type: application/json

### Get hotel by ID
GET http://localhost:8800/api/hotels/68bc51f97e5e7f053fe04e90
Content-Type: application/json

### Delete hotel
DELETE http://localhost:8800/api/hotels/68bc51f97e5e7f053fe04e90
Content-Type: application/json

### Register user
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
  "username": "john_bam",
  "email": "johnbam@example.com",
  "password": "password123"
}

### Login user
# POST http://localhost:8800/api/auth/login
# Content-Type: application/json

# {
#   "username": "john_bam",
#   "password": "password123"
# }

###Update user
GET  http://localhost:8800/api/users/checkauthentication
Content-Type: application/json

{
  "username": "john_updated"
}

###Check user
GET  http://localhost:8800/api/users/checkuser/68bc5fce3a723a315440c747
Content-Type: application/json

###Check admin
GET  http://localhost:8800/api/users/checkadmin/68bc5fce3a723a315440c747
Content-Type: application/json
